version: '3.8'
services:
  portfolio-web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run start
    #TODO: Add a health check for the service
    # healthcheck:  
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s