{
 "title": "Portfolio Cloud Run Service",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.service_name",
       "=",
       "portfolio-web",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/cpu/utilizations"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "portfolioproject-7841",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/container/memory/utilizations"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "portfolioproject-7841",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.service_name",
       "=",
       "portfolio-web",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "portfolioproject-7841",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Active Instance Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.service_name",
       "=",
       "portfolio-web",
       "AND",
       "metric.label.state",
       "=",
       "active",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/instance_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "none",
      "projectName": "portfolioproject-7841",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Idle Instance Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.service_name",
       "=",
       "portfolio-web",
       "AND",
       "metric.label.state",
       "=",
       "idle",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/instance_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "none",
      "projectName": "portfolioproject-7841",
      "view": "FULL"
     }
    }
   ]
  }
 ]
}