name: Azure CI/CD

on:
    push:
        branches:
            - azure-prod
    workflow_dispatch:

jobs:
    setup:
        name: Build and Deploy Job
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            
            - name: Install, Build, and Export
              run: |
                npm install
                npm run build
              working-directory: my-portfolio
              
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Azure Resources
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
                resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
                template: ./my-portfolio/Azure/main.bicep

            - name: Get SWA API Token
              id: get_api_token
              run: |
                TOKEN=$(az staticwebapp secrets list \
                  --name ${{ vars.AZURE_STATIC_WEB_APP_NAME }} \
                  --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
                  --query "properties.apiKey" -o tsv)
                echo "AZURE_STATIC_WEB_APPS_API_TOKEN=$TOKEN" >> $GITHUB_ENV
            
            - name: Deploy to Azure
              uses: Azure/static-web-apps-deploy@v1
              with:
                azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                action: 'upload'
                app_location: 'my-portfolio'
                api_location: 'my-portfolio'
                output_location: '.next'