name: Azure CI/CD

on:
    push:
        branches:
            - azure-prod
    workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
    setup:
        name: Build and Deploy Job
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install
              working-directory: my-portfolio
            
            - name: Build
              run: npm run build
              working-directory: my-portfolio

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az account show

            - name: Deploy Azure Resources
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
                resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
                template: my-portfolio/Azure/main.bicep
                parameters: >
                  location=eastus
                  swalocation=eastus2
                  resourceGroupName=${{ vars.AZURE_RESOURCE_GROUP_NAME }}
                  staticWebAppName=${{ vars.AZURE_STATIC_WEB_APP_NAME }}
                  sku=Free

            - name: Get Resource Group and Static Web App Name
              id: get_resources
              run: |
                RESOURCE_GROUP=$(az deployment sub show \
                  --name deployStaticWebApp \
                  --query "properties.outputs.resourceGroupName.value" -o tsv)
                STATIC_WEB_APP_NAME=$(az deployment sub show \
                  --name deployStaticWebApp \
                  --query "properties.outputs.staticWebAppName.value" -o tsv)
                echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV
                echo "STATIC_WEB_APP_NAME=$STATIC_WEB_APP_NAME" >> $GITHUB_ENV

            - name: Get Azure Static Web Apps API Token
              id: get_api_token
              run: |
                API_TOKEN=$(az staticwebapp secrets list \
                  --name $STATIC_WEB_APP_NAME \
                  --resource-group $RESOURCE_GROUP \
                  --query "properties.apiKey" -o tsv)
                echo "AZURE_STATIC_WEB_APPS_API_TOKEN=$API_TOKEN" >> $GITHUB_SECRETS
            
            - name: Deploy to Azure
              uses: Azure/static-web-apps-deploy@v1
              with:
                azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                action: 'upload'
                app_location: '/my-portfolio'
                api_location: 'my-portfolio/api'
                output_location: '.next'