name: Azure CI/CD

on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - azure-dev
    #         - azure-prod

jobs:
    setup:
        name: Setup Azure
        runs-on: ubuntu-latest

        # steps:
        
    deploy:
        if: github.ref == 'refs/heads/azure-prod'

        name: Deploy to Azure
        runs-on: ubuntu-latest
        needs: setup
        # environment: azure-prod
        
        # steps:
            
