name: Build CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [my-portfolio]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use PAT from GitHub Secrets

      - name: Set Branch Tag
        id: branch_tag
        run: |
          # Extract and sanitize the branch name (only alphanumeric and dashes)
          BRANCH_NAME="${GITHUB_REF##*/}"

          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]-')

          echo "branch_tag=$SANITIZED_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./my-portfolio
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ steps.branch_tag.outputs.branch_tag }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:latest
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ steps.branch_tag.outputs.branch_tag }}
