name: GHCR cleanup

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - id: cleanup
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: ${{ github.event.repository.owner.type == 'Organization' && github.repository_owner || 'user' }}
          token: ${{ secrets.GHCR_TOKEN }}
          
          image-names: "!v"                       # Select all images not starting with 'v'
          image-tags: "!latest !dev !prod !main"  # Exclude these tags from deletion
          keep-n-most-recent: 5
          tag-selection: both
          cut-off: 30d

          # Optional safety: set to true for a dry-run to see what would be deleted
          dry-run: false
