name: CI/CD

on:
  push:
    branches:
      - prod
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [my-portfolio]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use PAT from GitHub Secrets

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "portfolioproject-7841"

      - name: Authenticate Docker with GCP Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set Branch Tag
        id: branch_tag
        run: |
          # Extract and sanitize the branch name (only alphanumeric and dashes)
          BRANCH_NAME="${GITHUB_REF##*/}"
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]-')
          echo "branch_tag=$SANITIZED_BRANCH_NAME" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./my-portfolio
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ env.branch_tag }}
            us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:latest
            us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ github.sha }}
            us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ env.branch_tag }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:latest
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ env.branch_tag }}

      - name: Push to GAR
        run: |
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:latest
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ env.branch_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref_name == 'prod'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "portfolioproject-7841"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portfolio-web \
            --image us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --set-env-vars="EMAIL=${{ secrets.PORTFOLIO_GMAIL_ADDRESS }}" \
            --set-env-vars="EMAIL_PASSWORD=${{ secrets.PORTFOLIO_GMAIL_PASSWORD }}" \
            --set-env-vars="RECEIVER_EMAIL=${{ secrets.PORTFOLIO_RECEIVER_EMAIL }}"

      - name: Cleanup Old Revisions
        run: |
          gcloud run revisions list \
            --service portfolio-web \
            --region us-central1 \
            --format="value(NAME)" \
            | tail -n +2 \
            | xargs -I {} gcloud run revisions delete {} --quiet --region us-central1