name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          /usr/local/bin/docker-compose version
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use PAT from GitHub Secrets

      - name: Build and Start Services with Docker Compose
        working-directory: ./my-portfolio
        run: |
          docker-compose up --build -d
          sleep 30 # Wait for services to start

          - name: Verify Service Health Status
          run: |
            docker-compose up --build -d
            sleep 30 # Wait for services to start
            docker-compose ps
  
      - name: Check Service Logs
        run: |
          docker logs $(docker ps -q --filter "name=portfolio-web")
  
      - name: Verify Open Ports
        run: |
          docker ps --filter "name=portfolio-web" --format "table {{.Names}}\t{{.Ports}}"

      - name: Push Image to GHCR with Docker Compose
        working-directory: ./my-portfolio
        run: docker-compose push
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Stop and Clean Up
        run: docker-compose down      