name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [my-portfolio]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use PAT from GitHub Secrets

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./my-portfolio
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref_name == 'main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      #* I believe this is not needed as we already logged in in previous job - testing it now
      # - name: Log in to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_TOKEN }} # Use PAT from GitHub Secrets

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          /usr/local/bin/docker-compose version

      - name: Start services with Docker Compose
        working-directory: ./my-portfolio
        run: |
          docker-compose pull
          docker-compose up -d
          sleep 30

      #! Add verify service health here - https://github.com/alsheikhhusam/PortfolioProject/issues/1

      - name: Push Image to GHCR with Docker Compose
        working-directory: ./my-portfolio
        run: docker-compose push
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Stop and Clean Up
        working-directory: ./my-portfolio
        run: docker-compose down