name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [my-portfolio]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use PAT from GitHub Secrets

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "portfolioproject-7841"

      - name: Authenticate Docker with GCP Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set Branch Tag
        id: branch_tag
        run: |
          # Extract and sanitize the branch name (only alphanumeric and dashes)
          BRANCH_NAME="${GITHUB_REF##*/}"
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]-')
          echo "branch_tag=$SANITIZED_BRANCH_NAME" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./my-portfolio
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ env.branch_tag }}
            us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:latest
            us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ github.sha }}
            us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ env.branch_tag }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:latest
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ env.branch_tag }}

      - name: Push to GAR
        run: |
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:latest
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/portfolio:${{ env.branch_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref_name == 'main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          /usr/local/bin/docker-compose version

      - name: Start services with Docker Compose
        working-directory: ./my-portfolio
        run: |
          docker-compose pull
          docker-compose up -d
          sleep 30

      #TODO: Add verify service health here - https://github.com/alsheikhhusam/PortfolioProject/issues/1

      - name: Push Image to GHCR with Docker Compose
        working-directory: ./my-portfolio
        run: docker-compose push
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Stop and Clean Up
        working-directory: ./my-portfolio
        run: docker-compose down