name: Terraform Destroy (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      terraform-destroy:
        description: 'Terraform Destroy'
        required: true
        default: 'false'
        type: choice
        options:
          - yes
          - no

jobs:
  destroy:
    if: github.event.inputs.terraform-destroy == 'true'

    runs-on: ubuntu-latest

    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_cloud_run_name: ${{ vars.GCP_CLOUD_RUN_NAME }}
      TF_VAR_private_ip: ${{ secrets.PRIVATE_IP }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_zone: ${{ vars.GCP_ZONE }}
      TF_VAR_vm_size: ${{ vars.GCP_VM_NAME }}
      TF_VAR_vpc_network_name: ${{ vars.GCP_VPC_NETWORK_NAME }}
      TF_VAR_subnetwork_name: ${{ vars.GCP_SUBNETWORK_NAME }}
      TF_VAR_grafana_service_account_name: ${{ vars.GCP_GRAFANA_SA_NAME }}
      TF_VAR_gcp_artifact_registry_url: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Google Cloud Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: my-portfolio/terraform
        
      - name: Run Terraform Destroy
        run: |
          echo "Executing terraform destroy"
          terraform destroy -auto-approve
        working-directory: my-portfolio/terraform